### ISSUE TITLE
choice for different portals

### ISSUE THREAD

**Issue by ihubgit** [SkyLabs-Innovation-Group/SkyDrop#104]
title says it all : would be nice to be able to select more than one portal for Sia.

**Comment by wellhat** [comment]
Thanks @ihubgit. Long been a feature I have been meaning to add. Your task is in our todo list https://siasky.net/rAA_As-xjYDoBmk6gDAOEMiOCfX9k_8rSVIvU1n30elM3A

**Comment by wellhat** [comment]
@tomShoutTheSecond I've marked this as ready for review, you had reviewed most of the logic, I've just added some UIs that you can scrutinise if you like :)

**Comment by wellhat** [comment]
@ihubgit SkyDrop 1.1.0.0 is submitted and awaiting approval from Google/Apple. This update adds support for customising your Skynet portal :)
