### ISSUE TITLE
request - Skydrop app availability on F-Droid

### ISSUE THREAD

**Issue by JackPala** [SkyLabs-Innovation-Group/SkyDrop#109]
Love the app, but a lot of us are not using google services and instead rely on google-free stores such as F-droid. are there any plans for F-droid implementation?

**Comment by wellhat** [comment]
We have a listing on Skydroid which is also open source and secure! No
plans yet for an fdroid listing. https://skydroid.app/

**Comment by JackPala** [comment]
What Collection is it listed on on Skydroid?

**Comment by wellhat** [comment]
If you search the bundle ‘skydrop’ it should appear
