### ISSUE TITLE
Confirm that microphone permission is no longer being requested

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#115]
I'm upgrading to Xamarin.Essentials 1.7.0 which claims to have fixed that issue 

https://docs.microsoft.com/en-us/xamarin/essentials/release-notes/1.7

I also removed the microphone permission description from info.plist and added some new permissions which I think caused some crashes reported on AppCenter

Still need to confirm that this has actually worked bc my iPhone 7 doesn't request any permissions for some reason..?

Edit:

@tomShoutTheSecond if you could QA this on the iOS release candidate later it'd be helpful, idk why on my device permissions aren't being requested

**Comment by tomShoutTheSecond** [comment]
App doesn't request microphone permissions now 🎉
