### ISSUE TITLE
iOS upload tracking improvements

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#121]
I expected this to be simple to implement on iOS, given that it already worked on Android and the code is cross platform for this part, but due to an internal issue with the framework it breaks uploading on iOS when the improved tracking is enabled.

For now the next iOS release is delayed until I can get this feature working.

**Comment by tomShoutTheSecond** [comment]
I think we decided not to do this @wellhat ? Should we close this ticket?
