### ISSUE TITLE
Local file storage

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#157]
On Android check relation to https://app.gitkraken.com/glo/view/card/d7dbf21cb9c648938a7d555065f039fa

**Comment by tomShoutTheSecond** [comment]
Lol what is this ticket

**Comment by wellhat** [comment]
@tomShoutTheSecond it's the part of SkyDrive which handles local file caches. It's in "Needs Refinement" because it lacks info and potentially relates to several other tasks.

Includes:

* Handling of Android local files (atm it copies them over and leaves traces as discussed) 
* Handling of iOS local files (bit of a ? for me atm, I don't know what is possible yet for this on iOS)
* UI for caching / uncaching one or more files, so that user can easily set which files are cached on device and which are to be left as cloud files on Skydrive

**Comment by tomShoutTheSecond** [comment]
Closing this ticket because it duplicates https://app.gitkraken.com/glo/view/card/d7dbf21cb9c648938a7d555065f039fa

We discussed user determined file caching and decided it was not achievable
