### ISSUE TITLE
Files are being cached in the Skydrop app directory

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#158]
We are seeing files being copied to the temp folder on Android before upload. They are not getting deleted, so they are wasting storage space.

The new iOS multiple image selection also relies on the temp folder, so let's just make sure it gets cleared after file upload.

**Comment by wellhat** [comment]
Clear temp folder on app hard close

**Comment by tomShoutTheSecond** [comment]
I have fixed this on my branch feature/receive-files-integrated-view

Solution: put "temp" files in the temp cache folder, and files that the user has manually downloaded in the MyDocuments folder. Then we clear only the temp folder after uploading, MyDocuments folder does not get cleared so user can keep their saved files.
