### ISSUE TITLE
iOS - QR code is blurry on newer iPhones

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#194]
On iPhone 6 the QR code is crisp

On iPhone 11 Pro the QR code is blurry

Looks like the QR code resolution needs to be multiplied by the screen density factor when generating the BitMatrix

This does not appear to affect Android

**Comment by tomShoutTheSecond** [comment]
Fixed https://github.com/SkyLabs-Innovation-Group/SkyDrop/pull/219
