### ISSUE TITLE
Fix Realms.Exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'SkyFile.FileSizeBytes' has been added. in NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider)

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#21]
### Stacktrace ###

Realms.NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider) [0x00011] in <071e0b71ec454379b1024e32d809a8cb>:0;Realms

Realms.SharedRealmHandle.Open (Realms.Native.Configuration configuration, Realms.Schema.RealmSchema schema, System.Byte[] encryptionKey) [0x00024] in <071e0b71ec454379b1024e32d809a8cb>:0;Realms

Realms.RealmConfiguration.CreateRealm (Realms.Schema.RealmSchema schema) [0x00096] in <071e0b71ec454379b1024e32d809a8cb>:0;Realms

Realms.Realm.GetInstance (Realms.RealmConfigurationBase config, Realms.Schema.RealmSchema schema) [0x00016] in <071e0b71ec454379b1024e32d809a8cb>:0;Realms

Realms.Realm.GetInstance (Realms.RealmConfigurationBase config) [0x0000a] in <071e0b71ec454379b1024e32d809a8cb>:0;Realms

SkyDrop.Core.Services.StorageService.LoadSkyFiles () [0x00001] in <939cb75dadd34dbdb4c84ad8799ee819>:0;SkyDrop.Core.Services

SkyDrop.Core.ViewModels.Main.FilesViewModel.LoadSkyFiles () [0x00001] in <939cb75dadd34dbdb4c84ad8799ee819>:0;SkyDrop.Core.ViewModels.Main

SkyDrop.Core.ViewModels.Main.FilesViewModel.Initialize () [0x00001] in <939cb75dadd34dbdb4c84ad8799ee819>:0;SkyDrop.Core.ViewModels.Main

MvvmCross.ViewModels.MvxDefaultViewModelLocator+<>c__DisplayClass6_0.<RunViewModelLifecycle>b__0 () [0x00000] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.ViewModels

MvvmCross.ViewModels.MvxNotifyTask.Create (System.Func`1[TResult] asyncAction, System.Action`1[T] onException) [0x00000] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.ViewModels

MvvmCross.ViewModels.MvxDefaultViewModelLocator.RunViewModelLifecycle (MvvmCross.ViewModels.IMvxViewModel viewModel, MvvmCross.ViewModels.IMvxBundle parameterValues, MvvmCross.ViewModels.IMvxBundle savedState, MvvmCross.Navigation.EventArguments.IMvxNavigateEventArgs navigationArgs) [0x00093] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.ViewModels

### Reason ###

Realms.Exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'SkyFile.FileSizeBytes' has been added.

### Link to App Center ###

* [https://appcenter.ms/users/wellhat/apps/SkyDrop/crashes/errors/1401448047u](https://appcenter.ms/users/wellhat/apps/SkyDrop/crashes/errors/1401448047u)

**Comment by tomShoutTheSecond** [comment]
I fixed this with some changes to StorageService in this PR https://github.com/SkyLabs-Innovation-Group/SkyDrop/pull/22

It means that all local data gets destroyed when a migration is required by Realm (usually when one of the RealmObject data model classes is modified
