### ISSUE TITLE
Warning about how the data cannot be deleted once uploaded

### ISSUE THREAD

**Issue by tomShoutTheSecond** [SkyLabs-Innovation-Group/SkyDrop#25]
Only show this once

Also mention how the files are not encrypted

Add onboarding for the swipe gesture

**Comment by wellhat** [comment]
@tomShoutTheSecond

I kind of think we should just link the Skynet/Siasky privacy policy in a dialog the first time they open the app, perhaps? Or could show it in a settings screen. Thoughts?

**Comment by tomShoutTheSecond** [comment]
@wellhat Yeah good idea!

**Comment by wellhat** [comment]
Am personally happy with how we're set up without the in-app notification which just adds clutter and complexity to our UI. I think privacy policy +

**Comment by tomShoutTheSecond** [comment]
@wellhat I agree, think it's fine now how it is
