### ISSUE TITLE
Select Media feature

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#33]
Should we keep the select image option and open the default media browser with multi select enabled? Otherwise, we could simply remove the dialog entirely and just support multi file select - I think it's still fairly easy on both platforms to select media this way. 

What do you think is the desired UX @tomShoutTheSecond?

**Comment by tomShoutTheSecond** [comment]
@wellhat I think it's best to let the user choose whether to browse with their gallery app or their file browser app

**Comment by wellhat** [comment]
@tomShoutTheSecond Yeah, I think that's true. Okay, I'll try and add support for this, but I don't like how it separates images/video sometimes

**Comment by wellhat** [comment]
We decided on a select media feature

**Comment by wellhat** [comment]
I think this is one we're not doing now
