### ISSUE TITLE
Grid swipe UI

### ISSUE THREAD

**Issue by tomShoutTheSecond** [SkyLabs-Innovation-Group/SkyDrop#39]
Create a grid style layout where one element is visible at a time, and users can swipe up / down / left / right to change the current view

- Send / Receive buttons
- QR Code
- My Files

**Comment by wellhat** [comment]
Swipe up to advanced upload options @tomShoutTheSecond

Some inspiration:

https://about.instagram.com/blog/engineering/on-building-a-fluid-user-interface?utm_campaign=Weekly%2BXamarin&utm_medium=email&utm_source=Weekly_Xamarin_306

**Comment by wellhat** [comment]
Due to being a large undertaking I've moved this back to the backlog
