### ISSUE TITLE
Lock Portrait Orientation

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#5]
Required because rotation is breaking the UI

**Comment by wellhat** [comment]
Not sure that we can do this anymore... @tomShoutTheSecond

**Comment by tomShoutTheSecond** [comment]
@wellhat Why not?

**Comment by wellhat** [comment]
Can't find anything about how to do it now

**Comment by tomShoutTheSecond** [comment]
@wellhat Completed on android

**Comment by tomShoutTheSecond** [comment]
Completed on iOS
