### ISSUE TITLE
Fix System.InvalidCastException: Specified cast is not valid. in MvxAsyncCommand`1[T].ExecuteAsyncImpl (System.Object parameter)

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#69]
### Stacktrace ###

MvvmCross.Commands.MvxAsyncCommand`1[T].ExecuteAsyncImpl (System.Object parameter) [0x00016] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.Commands

MvvmCross.Commands.MvxAsyncCommandBase.ExecuteConcurrentAsync (System.Object parameter, System.Boolean hideCanceledException) [0x000a7] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.Commands

MvvmCross.Commands.MvxAsyncCommandBase.ExecuteAsync (System.Object parameter, System.Boolean hideCanceledException) [0x00085] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.Commands

MvvmCross.Commands.MvxAsyncCommandBase.Execute (System.Object parameter) [0x0009a] in <687f2e5f7efd4e33b498a18ba9db221f>:0;MvvmCross.Commands

### Reason ###

System.InvalidCastException: Specified cast is not valid.

### Link to App Center ###

* [https://appcenter.ms/users/wellhat/apps/SkyDrop/crashes/errors/743809484u](https://appcenter.ms/users/wellhat/apps/SkyDrop/crashes/errors/743809484u)

**Comment by tomShoutTheSecond** [comment]
I don't think there's enough info here to fix this. Probably just a mistake during development.
