### ISSUE TITLE
QR generation is slow

### ISSUE THREAD

**Issue by wellhat** [SkyLabs-Innovation-Group/SkyDrop#7]
Allow users to copy skylinks / open files / share skylinks while the QR code is being generated. (done)

optionally we could optimise the QR code generation by doing it at a lower resolution
a better optimisation would be to split the QR into 4 (or 9, 16 etc), then generate each corner of the bitmap concurrently

**Comment by wellhat** [comment]
Found https://github.com/mono/SkiaSharp/issues/416

I think there will be ways to do this more efficiently, I had some ideas but wasn't able to get it working immediately. There should be an efficient way to load the bytes into a buffer, then load those bytes into the ImageView

**Comment by tomShoutTheSecond** [comment]
Found this which looks relevant, there are various "Renderer" classes included with ZXing that may have optimised conversion for bitmaps etc https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/renderer/PixelData.AndroidBitmap.cs

**Comment by tomShoutTheSecond** [comment]
I can quickly convert to a PixelData object using PixelDataRenderer on iOS at least, but not sure how to convert PixelData -> UIImage

**Comment by tomShoutTheSecond** [comment]
Think I may have found the solution https://github.com/Redth/ZXing.Net.Mobile/blob/master/ZXing.Net.Mobile/iOS/BitmapRenderer.ios.cs

**Comment by tomShoutTheSecond** [comment]
Fixed on main
